# GRAPHICS SETTINGS ---
graphics:
  gibs: 2 # 0 -> none; 1 -> normal; 2 -> extra
  fullscreen: false # Whether or not the game should start in fullscreen

# --- GRAPHICS SETTINGS

# AUDIO SETTINGS ---
audio:
  musicVolume: -4.0 # Decibles difference on volume, -4 by default (loud music!)

# --- AUDIO SETTINGS